#!usr/bin/env python3

import requests
import pprint
import json


def main():
    url = "https://sandboxdnac.cisco.com/dna/intent/api/v1/network-device/1cfd383a-7265-47fb-96b3-f069191a0ed5/config"

    payload = {}
    headers = {
        'x-auth-token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1ZTlkYmI3NzdjZDQ3ZTAwNGM2N2RkMGUiLCJhdXRoU291cmNlIjoiaW50ZXJuYWwiLCJ0ZW5hbnROYW1lIjoiVE5UMCIsInJvbGVzIjpbIjVkYzQ0NGQ1MTQ4NWM1MDA0YzBmYjIxMiJdLCJ0ZW5hbnRJZCI6IjVkYzQ0NGQzMTQ4NWM1MDA0YzBmYjIwYiIsImV4cCI6MTU4ODkyMzU0MiwiaWF0IjoxNTg4OTE5OTQyLCJqdGkiOiIxMGRlZWJjNy0xNzU2LTRlNTMtYmU5OC05MjRiYjBlZWM5ZWIiLCJ1c2VybmFtZSI6ImRldm5ldHVzZXIifQ.Ffk_OtZJkrsxMBY2czmJ-3WU7XmR2v8yma1jF5IVFn-4qzGnQN_k7nHlt55Z3Zg4z3bIK5Sh4ChAHSsqZ5JxkmgMP0QVMBdFszvduijL-sq1w2XLP2-Qa_eIFt4CgCfSjQ8fjVUXrETcE2kcxahdguJZWdm2cmAVOxLg-ddk9rMY-Ic0XSdBxtG9fXEADXsMOhe7j2vVX7l9gO-DC3Am-3RinlR8nQvXm9TD635uchAewPNgWXwnLqvu5NhUUbug5yH_nyhtgts2vKNo-HWqgJ6xd-rjprWSk4d8LgUyGpsE1XfvcDLpyJa7cl_qb5WO4T3srSR1CIAawoE2xdKTTg',
        'Authorization': 'Basic ZGV2bmV0dXNlcjpDaXNjbzEyMyE    =',
        'Cookie': 'JSESSIONID=110eauy5ac0481r8rhkw4p7iw3'
    }

    response = requests.request("GET", url, headers=headers, data=payload)

    running_config = response.json()["response"]
    print("ASR config below: \n")
    print(running_config, flush=True)


if __name__ == '__main__':
    main()
